### ISSUE TITLE
Azure Blob Storage megaissue - PR breakdown

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#3298]
I'm breaking down the various PRs involved with Azure Blob Storage in this megaissue (this is all for solving issue #3112).

## Entire PR
https://github.com/codalab/codalab-worksheets/pull/3198 - don't review this, but it may be good to use as a reference, as it includes the state of the codebase when all the individual PRs are combined.

## PRs that are ready to be reviewed
These PRs split the work from the above PR and are ready to be reviewed:
- [x] Add bundle `storage_type` and `is_dir` columns to the database - #3300
- [x] Update requirements, add new args to codalab-service - #3304
- [x] Add `--use-azure-blob-beta` argument to bundle CLI - #3305
- [x] Add the `MultiDiskBundleStoreWithBlobStorage` bundle store - #3306
- [ ] Add download_util.py changes to work with downloading / reading from Azure Blob Storage - #3309

## PRs that should be reviewed in the future
These PRs are in draft status and depend on other PRs from above, so they should not be reviewed until the ones above are merged:

- [ ] Update upload and download logic to work with Azure Blob Storage - #3308

**Comment by epicfaace** [comment]
Closing this in favor of the other blob storage issues; most of the PRs in this issue (except for #3308) have already been merged.
