### ISSUE TITLE
singularity support megaissue

### ISSUE THREAD

**Issue by adiprerepa** [codalab/codalab-worksheets#3661]
This issue is to track the progress of all singularity issues.

Initial Investigation Issue: https://github.com/codalab/codalab-worksheets/issues/3284

Design doc: https://docs.google.com/document/d/1QfH3xk84xByjrK19BwcbrZ87_F2LJe4MAbts5hx4nBE/edit

## Issues that need to be worked on
- [ ] https://github.com/codalab/codalab-worksheets/issues/3655 ([PR](https://github.com/codalab/codalab-worksheets/pull/3569)) - week of July 9
- [x] https://github.com/codalab/codalab-worksheets/issues/3656
- [x] https://github.com/codalab/codalab-worksheets/issues/3657
- [x] https://github.com/codalab/codalab-worksheets/issues/3658
- [x] https://github.com/codalab/codalab-worksheets/issues/3660

everything done - mid-to-end July

There will probably be more as more work arises, which will be added to this list.

## PRs for associated issues
- https://github.com/codalab/codalab-worksheets/pull/3569
