### ISSUE TITLE
Multi-bundle store megaissue

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#3799]
This is based on the following design doc: https://docs.google.com/document/d/1TOsO4gnxUm1XMmlGUb7BJ4Z6y_olFbv9APbx0-IEy6M/edit#

### Backend - Aditya / Ashwin
- [x] https://github.com/codalab/codalab-worksheets/issues/3792 - 10/27
- [ ] https://github.com/codalab/codalab-worksheets/issues/3802 - EOW 12/4
- [ ] https://github.com/codalab/codalab-worksheets/issues/3779 - 12/14
- [ ] Extend blob storage implementation to support GCS - ?

### CLI / REST API
- [ ] https://github.com/codalab/codalab-worksheets/issues/3800 - Aditya - EOW 12/4
- [x] https://github.com/codalab/codalab-worksheets/issues/3801 - Andy and Ashwin - EOW 12/4
- [x] Set up mock bundle store CLI commands #3827 - Jizhen
   - [ ] Implement the CLI commands https://github.com/codalab/codalab-worksheets/issues/3803 (blocked on the REST endpoints) - Jizhen - week of 12/8

### Frontend website - Jizhen - 12/14
- [x] #3858
- [x] #3859

## Issues to work on at some time in the future

- [x] https://github.com/codalab/codalab-worksheets/issues/3804
- [x] https://github.com/codalab/codalab-worksheets/issues/3805
- allow users to create BYO bundle stores

**Comment by epicfaace** [comment]
Closing as this task list is pretty outdated now.
