### ISSUE TITLE
Bundle Detail UI Fixes (6)

### ISSUE THREAD

**Issue by teetone** [codalab/codalab-worksheets#4169]
### Tasks
- [x] Show an error message if bundle doesn't exist
    * **Example:**  https://codalab.stanford.edu/bundles/0x449b925399d547c0b2f5ee0150a5121a
- [x] Update the state box tooltips to use the same font size as the field name tooltips
- [x] Add proper field names to tooltips
- [x] Fix Permissions overflow
    * **Example:** https://worksheets.codalab.org/bundles/0x466051121f684894bdf59ac4a0567dfc
- [x] Confirm that each field has a tooltip
    * Run Bundles
    * Uploaded Bundles
    * Make Bundles
- [x] Confirm that tooltips are showing up when viewing a bundle that you don't own
    * **Example:** Staged bundles that I don't own https://worksheets.codalab.org/worksheets/0xa590fd1b68944a1a95c1c40c4931dc7b

**Comment by leilenah** [comment]
Reference for how we handle missing worksheets:

![Screen Shot 2022-08-01 at 7 51 41 PM](https://user-images.githubusercontent.com/25855750/182281536-59a886a0-f1c8-497d-aedd-3067eab06dfe.png)

**Comment by leilenah** [comment]
@pranavjain if you have additional notes on the bundle detail UI, feel free to comment them here. I have captured a couple notes that came up during the last weekly meeting.

**Comment by leilenah** [comment]
Will address https://github.com/codalab/codalab-worksheets/issues/4165 here.

**Comment by leilenah** [comment]
### Meeting Notes
* list of things that can't be change
* only things in the top should be editable 
* remove ability to edit things
* get rid of the ability to edit things after the fact (could do this on the backend)
* you should be able to change things that are still staged
* lock fields once starting
* open separate google doc to discuss these fields
* general framework for fields 
* for now hide the field if its none and can't edit it
* potentially move time up above into main area
* Re-label `time` to something that makes more sense
