### ISSUE TITLE
[Migration] Convert `program` bundles to `dataset` bundles

### ISSUE THREAD

**Issue by leilenah** [codalab/codalab-worksheets#4235]
### Overview
`program` bundles were deprecated a while back. A program bundle is a bundle with **bundle_type** `program`. However, there are some lingering `program` bundles in the prod database. We should run a migration to convert these bundles to `dataset` bundles.

### Tasks
- [ ] Run a migration to convert bundles with `program` **bundle_type** to have a `dataset` **bundle_type**.
- [ ] Remove references to the [ProgramBundle](https://github.com/codalab/codalab-worksheets/blob/master/codalab/bundles/program_bundle.py) class from the codalab-worksheets repo
- [ ] Remove defensive checks from `get_bundle_state_details()` helper function
    - **Context:** https://github.com/codalab/codalab-worksheets/pull/4229

### Related Issues
https://github.com/codalab/codalab-worksheets/issues/4228
